RETURN_TRANSITIONS = {
    "SUBMITTED": {"RECEIVED", "REJECTED", "CANCELLED", "CLOSED_EXPIRED"},
    "RECEIVED": {"QC_IN_PROGRESS", "REJECTED"},
    "QC_IN_PROGRESS": {"QC_APPROVED", "WAITING_FOR_EXCHANGE_PAYMENT", "EXCHANGE_PROCESSING", "REJECTED"},
    "QC_APPROVED": {"WAITING_FOR_STOCK", "WAITING_FOR_EXCHANGE_PAYMENT", "EXCHANGE_PROCESSING", "REFUND_PROCESSING"},
    "WAITING_FOR_STOCK": {"QC_APPROVED", "WAITING_FOR_EXCHANGE_PAYMENT", "EXCHANGE_PROCESSING", "CANCELLED"},
    "WAITING_FOR_EXCHANGE_PAYMENT": {"EXCHANGE_PROCESSING", "CANCELLED", "CLOSED_EXPIRED"},
    "EXCHANGE_PROCESSING": {"COMPLETED"},
    "REFUND_PROCESSING": {"COMPLETED"},
}

WARRANTY_TRANSITIONS = {
    "SUBMITTED": {"RECEIVED", "REJECTED", "CANCELLED", "CLOSED_EXPIRED"},
    "RECEIVED": {"QC_IN_PROGRESS", "REJECTED"},
    "QC_IN_PROGRESS": {"WARRANTY_ACCEPTED", "REPLACEMENT_APPROVED", "REJECTED"},
    "WARRANTY_ACCEPTED": {"REPAIRING", "READY_TO_RETURN"},
    "REPAIRING": {"READY_TO_RETURN"},
    "REPLACEMENT_APPROVED": {"WAITING_FOR_STOCK", "REPLACEMENT_PROCESSING"},
    "WAITING_FOR_STOCK": {"REPLACEMENT_APPROVED", "REPLACEMENT_PROCESSING", "CANCELLED"},
    "REPLACEMENT_PROCESSING": {"READY_TO_RETURN", "COMPLETED"},
    "READY_TO_RETURN": {"COMPLETED"},
}


def transitions_for(kind: str) -> dict[str, set[str]]:
    return RETURN_TRANSITIONS if kind == "RETURN" else WARRANTY_TRANSITIONS


def label_for(kind: str) -> str:
    return "đổi trả" if kind == "RETURN" else "bảo hành"
